# Generated by Django 4.0.4 on 2022-06-04 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localización', models.CharField(max_length=60, verbose_name='Localización')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro', verbose_name='Título del libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dev', models.DateField(verbose_name='Fecha de Devolución')),
                ('fecha_pres', models.DateField(verbose_name='Fecha de Préstamo')),
                ('ejemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ejemplares.ejemplar', verbose_name='Ejemplar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='usuario',
            field=models.ManyToManyField(through='ejemplares.Prestamo', to=settings.AUTH_USER_MODEL),
        ),
    ]
