# Generated by Django 4.0.4 on 2022-06-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplar',
            old_name='localización',
            new_name='localizacion',
        ),
    ]
